### ISSUE TITLE
Unable to Execute detect-smells-plugin: Invalid Environment Settings

### ISSUE THREAD

**Issue by LichiY** [AlshammariA/FlakeFlagger#6]
I encountered an issue while trying to execute the detect-smells-plugin for the dbdeploy-core project. The build fails with the error invalid environment settings. Below are the details of the error and steps I have taken to try to resolve it.

**Environment:**

- Operating System: Windows 10
- JDK Version: 1.8.0_181
- Maven Version: Apache Maven 3.3.9
- Project: dbdeploy
- Plugin: detect-smells-plugin 1.0-SNAPSHOT

**Error Log:**

> [ERROR] Failed to execute goal edu.gmu.swe.smells:detect-smells-plugin:1.0-SNAPSHOT:detectSmells (test-smells-report-tests) on project dbdeploy-core: Execution test-smells-report-tests of goal edu.gmu.swe.smells:detect-smells-plugin:1.0-SNAPSHOT:detectSmells failed: invalid environment settings -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal edu.gmu.swe.smells:detect-smells-plugin:1.0-SNAPSHOT:detectSmells (test-smells-report-tests) on project dbdeploy-core: Execution test-smells-report-tests of goal edu.gmu.swe.smells:detect-smells-plugin:1.0-SNAPSHOT:detectSmells failed: invalid environment settings
    ...
Caused by: java.lang.IllegalStateException: invalid environment settings
    at org.eclipse.jdt.core.dom.ASTParser.getClasspath(ASTParser.java:261)
    at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:993)
    at edu.gmu.swe.smells.detector.internal.JDTContext.collectAllTypes(JDTContext.java:119)
    at edu.gmu.swe.smells.detector.internal.JDTContext.<init>(JDTContext.java:30)
    at edu.gmu.swe.smells.detector.internal.DetectorEntryPoint.buildTestContextMap(DetectorEntryPoint.java:166)
    at edu.gmu.swe.smells.detector.maven.TestSmellDetectorMojo.execute(TestSmellDetectorMojo.java:306)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 22 more

I need assistance to resolve the invalid environment settings error encountered while executing the detect-smells-plugin. Any insights or suggestions on how to fix this issue would be greatly appreciated.

Thank you.

**Comment by jon-bell** [comment]
Could you please share:
1. The *complete* log output of the command that you used to run maven and
2. A link to the repository that you tried to use it on?

**Comment by LichiY** [comment]
> Could you please share:
> 
> 1. The _complete_ log output of the command that you used to run maven and
> 2. A link to the repository that you tried to use it on?

[maven-full.log](https://github.com/AlshammariA/FlakeFlagger/files/15318074/maven-full.log)
https://github.com/tackley/dbdeploy
thank you.

**Comment by jon-bell** [comment]
I succeeded running the tool with the same version of maven and Java on that project, on Mac. I do not have easy access to a windows machine - it is possible (likely?) that there are path separator comparison issues that might cause this. Do you have access to a Mac or linux machine to test?

**Comment by LichiY** [comment]
> I succeeded running the tool with the same version of maven and Java on that project, on Mac. I do not have easy access to a windows machine - it is possible (likely?) that there are path separator comparison issues that might cause this. Do you have access to a Mac or linux machine to test?

ok,thank you very much . I will try it.
